/* ==========================================================================
   Data bootstrap
   The dashboard expects `window.APP_DATA` to be defined by `js/data.js`
   (generated by `python/build_data.py` from the daily CSV).
   ========================================================================== */
if (!window.APP_DATA) {
  console.error(
    'window.APP_DATA is missing — run `python3 python/build_data.py` ' +
    'to generate js/data.js before opening the dashboard.'
  );
}
const APP_DATA = window.APP_DATA || { realtime: { shelter: [], compounds: [], outdoor: [] }, analysis: null };

// Real-time snapshot (latest-month aggregate computed by the Python builder)
const dashboardData = APP_DATA.realtime;

/* ==========================================================================
   Composting phases (Mesofílica · Termofílica · Enfriamiento · Maduración)
   Detected from the middle-zone temperature (compost core) as short cycle
   stages: a brief mesophilic warm-up, a thermophilic peak, then cooling and
   maturation. This keeps mesophilic from stretching across long warm periods.
   ========================================================================== */
const PHASES = {
  mesophilic: {
    id: 'mesophilic',
    label: 'Mesophilic',
    short: 'Meso',
    color: '#3ddc97',
    band: 'rgba(61, 220, 151, 0.10)',
    ring: 'rgba(61, 220, 151, 0.55)',
    description: '20–40 °C · active mesophilic bacteria (start-up)'
  },
  thermophilic: {
    id: 'thermophilic',
    label: 'Thermophilic',
    short: 'Thermo',
    color: '#ff6b6b',
    band: 'rgba(255, 107, 107, 0.14)',
    ring: 'rgba(255, 107, 107, 0.60)',
    description: '> 40 °C · peak activity, pathogens eliminated'
  },
  cooling: {
    id: 'cooling',
    label: 'Cooling',
    short: 'Cool',
    color: '#ffb84d',
    band: 'rgba(255, 184, 77, 0.12)',
    ring: 'rgba(255, 184, 77, 0.55)',
    description: 'Descent from the thermophilic peak back to 20–30 °C'
  },
  maturation: {
    id: 'maturation',
    label: 'Maturation',
    short: 'Mat',
    color: '#6dd3ff',
    band: 'rgba(109, 211, 255, 0.12)',
    ring: 'rgba(109, 211, 255, 0.55)',
    description: '< 20 °C · final stabilization, cured compost'
  }
};

const PHASE_ORDER = ['mesophilic', 'thermophilic', 'cooling', 'maturation'];
const analysisData = APP_DATA.analysis || {
  labels: [],
  outdoor: { temperature: [], humidity: [] },
  compound1: {
    temperature: { top: [], middle: [], bottom: [] },
    humidity: { top: [], middle: [], bottom: [] },
    heating: []
  },
  compound2: {
    temperature: { top: [], middle: [], bottom: [] },
    humidity: { top: [], middle: [], bottom: [] },
    heating: []
  }
};

const phaseSeriesCache = new Map();

function normalizePhaseTemp(value) {
  if (value == null || isNaN(value)) return null;

  // The CSV uses 0 for sensor dropouts in the compost core series.
  // Treat those readings as gaps so phases do not jump backwards.
  return value <= 0 ? null : value;
}

function average(values) {
  if (!values.length) return null;
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function buildRollingAverages(temps) {
  const recentTemps = [];

  return temps.map((temp) => {
    if (temp == null) return null;

    recentTemps.push(temp);
    if (recentTemps.length > 3) recentTemps.shift();
    return average(recentTemps);
  });
}

function findThermophilicRuns(temps, rollingAverages) {
  const runs = [];
  let currentRun = null;

  for (let i = 0; i < temps.length; i++) {
    const temp = temps[i];
    const avgTemp = rollingAverages[i];
    const isHot = temp != null && (temp >= 40 || avgTemp >= 40);

    if (isHot) {
      if (!currentRun) currentRun = { start: i, end: i };
      else currentRun.end = i;
    } else if (currentRun) {
      runs.push(currentRun);
      currentRun = null;
    }
  }

  if (currentRun) runs.push(currentRun);
  return runs;
}

function collectMesophilicWindow(temps, rollingAverages, runStart, lowerBound) {
  const window = [];

  for (let i = runStart - 1; i >= lowerBound && window.length < 3; i--) {
    const temp = temps[i];
    const avgTemp = rollingAverages[i];
    const isWarm = temp != null && (temp >= 20 || avgTemp >= 20);

    if (!isWarm) break;
    window.push(i);
  }

  return window.reverse();
}

function findMaturationStart(temps, start, end) {
  const recentTemps = [];
  let stableLowStreak = 0;

  for (let i = start; i <= end; i++) {
    const temp = temps[i];
    if (temp == null) continue;

    recentTemps.push(temp);
    if (recentTemps.length > 3) recentTemps.shift();

    const avgTemp = average(recentTemps);
    const isStableLow = avgTemp != null && avgTemp <= 25;

    stableLowStreak = isStableLow ? stableLowStreak + 1 : 0;
    if (stableLowStreak >= 3) return i;
  }

  return null;
}

function buildPhaseSeries(temps) {
  const normalizedTemps = temps.map(normalizePhaseTemp);
  const rollingAverages = buildRollingAverages(normalizedTemps);
  const thermophilicRuns = findThermophilicRuns(normalizedTemps, rollingAverages);
  const mesophilicWindows = thermophilicRuns.map((run, idx) => {
    const prevRun = idx > 0 ? thermophilicRuns[idx - 1] : null;
    const lowerBound = prevRun ? prevRun.end + 1 : 0;
    return collectMesophilicWindow(normalizedTemps, rollingAverages, run.start, lowerBound);
  });
  const series = new Array(temps.length).fill(null);

  thermophilicRuns.forEach((run, idx) => {
    for (let i = run.start; i <= run.end; i++) {
      series[i] = 'thermophilic';
    }

    mesophilicWindows[idx].forEach((i) => {
      series[i] = 'mesophilic';
    });
  });

  thermophilicRuns.forEach((run, idx) => {
    const nextRun = thermophilicRuns[idx + 1];
    const nextMesophilicWindow = nextRun ? mesophilicWindows[idx + 1] : [];
    const gapStart = run.end + 1;
    const gapEnd = nextMesophilicWindow.length
      ? nextMesophilicWindow[0] - 1
      : (nextRun ? nextRun.start - 1 : normalizedTemps.length - 1);

    if (gapStart > gapEnd) return;

    const maturationStart = findMaturationStart(normalizedTemps, gapStart, gapEnd);

    for (let i = gapStart; i <= gapEnd; i++) {
      if (normalizedTemps[i] == null) {
        series[i] = i > 0 ? series[i - 1] : null;
      } else if (maturationStart != null && i >= maturationStart) {
        series[i] = 'maturation';
      } else {
        series[i] = 'cooling';
      }
    }
  });

  for (let i = 1; i < series.length; i++) {
    if (normalizedTemps[i] == null && series[i] == null) {
      series[i] = series[i - 1];
    }
  }

  return series;
}

function detectPhase(temps, i) {
  if (i < 0 || i >= temps.length) return null;
  return buildPhaseSeries(temps)[i] || null;
}

function detectPhaseSingle(currentTemp, previousTemp) {
  if (currentTemp == null || isNaN(currentTemp)) return null;

  const temps = [previousTemp ?? currentTemp, currentTemp];
  return detectPhase(temps, temps.length - 1);
}

function getPhaseSeries(compoundKey) {
  if (!phaseSeriesCache.has(compoundKey)) {
    const temps = analysisData[compoundKey]?.temperature?.middle || [];
    phaseSeriesCache.set(compoundKey, buildPhaseSeries(temps));
  }

  return phaseSeriesCache.get(compoundKey) || [];
}

function getRealtimePhase(compound, index) {
  const compoundKey = `compound${index + 1}`;
  const phaseSeries = getPhaseSeries(compoundKey);

  if (phaseSeries.length) {
    return phaseSeries[phaseSeries.length - 1] || null;
  }

  return detectPhaseSingle(compound.middle.temperature, compound.prevMiddleTemp);
}
function tempStatus(value) {
  if (value == null) return '';
  if (value < 18) return 'status-low';
  if (value > 30) return 'status-high';
  return 'status-normal';
}

function humStatus(value) {
  if (value == null) return '';
  if (value < 40) return 'status-low';
  if (value > 70) return 'status-high';
  return 'status-normal';
}

function metricHTML(label, value, unit, statusClass) {
  if (value == null) {
    return `
      <div class="metric">
        <span class="label">${label}</span>
        <div class="value value-empty">--</div>
      </div>
    `;
  }

  return `
    <div class="metric">
      <span class="label">${label}</span>
      <div class="value ${statusClass}">${value}${unit}</div>
    </div>
  `;
}

function sensorCard(sensor) {
  const temperature = sensor.temperature != null ? sensor.temperature.toFixed(1) : null;
  const humidity = sensor.humidity != null ? sensor.humidity : null;

  return `
    <article class="card">
      <div class="card-title">
        <span class="card-name">${sensor.name}</span>
        <span class="pill">Current</span>
      </div>
      <div class="metrics">
        ${metricHTML('Temp', temperature, '°C', tempStatus(sensor.temperature))}
        ${metricHTML('Humidity', humidity, '%', humStatus(sensor.humidity))}
      </div>
    </article>
  `;
}

function phaseBadgeHTML(phaseId) {
  if (!phaseId || !PHASES[phaseId]) return '';
  const p = PHASES[phaseId];
  return `
    <span class="phase-badge phase-${p.id}" title="${p.description}">
      <span class="phase-dot"></span>
      <span class="phase-text">Phase: ${p.label}</span>
    </span>
  `;
}

function composterCard(compost, index) {
  const phaseId = getRealtimePhase(compost, index);
  return `
    <article class="composter">
      <div class="composter-head">
        <h3>${compost.title}</h3>
        <div class="composter-head-right">
          ${phaseBadgeHTML(phaseId)}
          <span class="pill">Top / Middle / Bottom</span>
        </div>
      </div>

      <div class="zones">
        <div class="zone top">
          <div class="zone-header">
            <div>
              <div class="zone-title">Top</div>
              <div class="zone-sub">Upper section</div>
            </div>
          </div>
          <div class="metrics">
            ${metricHTML('Temp', compost.top.temperature.toFixed(1), '°C', tempStatus(compost.top.temperature))}
            ${metricHTML('Humidity', compost.top.humidity, '%', humStatus(compost.top.humidity))}
          </div>
        </div>

        <div class="zone middle">
          <div class="zone-header">
            <div>
              <div class="zone-title">Middle</div>
              <div class="zone-sub">Middle section</div>
            </div>
          </div>
          <div class="metrics">
            ${metricHTML('Temp', compost.middle.temperature.toFixed(1), '°C', tempStatus(compost.middle.temperature))}
            ${metricHTML('Humidity', compost.middle.humidity, '%', humStatus(compost.middle.humidity))}
          </div>
        </div>

        <div class="zone bottom">
          <div class="zone-header">
            <div>
              <div class="zone-title">Bottom</div>
              <div class="zone-sub">Lower section</div>
            </div>
          </div>
          <div class="metrics">
            ${metricHTML('Temp', compost.bottom.temperature.toFixed(1), '°C', tempStatus(compost.bottom.temperature))}
            ${metricHTML('Humidity', compost.bottom.humidity, '%', humStatus(compost.bottom.humidity))}
          </div>
        </div>
      </div>

      <div class="heat-card">
        <span class="label">Interior Heating</span>
        <div class="value status-heat">${compost.heating.toFixed(1)} kWh</div>
      </div>
    </article>
  `;
}

function renderDashboard(data) {
  document.getElementById('shelter-grid').innerHTML = data.shelter.map(sensorCard).join('');
  document.getElementById('compounds-grid').innerHTML = data.compounds.map((compost, index) => composterCard(compost, index)).join('');
  document.getElementById('outdoor-grid').innerHTML = data.outdoor.map(sensorCard).join('');
}

renderDashboard(dashboardData);

const tabs = document.querySelectorAll('.tab');
const panels = document.querySelectorAll('.tab-panel');
let analysisInitialized = false;

tabs.forEach((tab) => {
  tab.addEventListener('click', () => {
    const target = tab.dataset.tab;

    tabs.forEach((t) => {
      const isActive = t === tab;
      t.classList.toggle('active', isActive);
      t.setAttribute('aria-selected', isActive ? 'true' : 'false');
    });

    panels.forEach((panel) => {
      const isActive = panel.id === `tab-${target}`;
      panel.classList.toggle('active', isActive);
      if (isActive) {
        panel.removeAttribute('hidden');
      } else {
        panel.setAttribute('hidden', '');
      }
    });

    if (target === 'analysis' && !analysisInitialized) {
      initAnalysisCharts();
      analysisInitialized = true;
    }
  });
});

function pearson(a, b) {
  const n = Math.min(a.length, b.length);
  let sx = 0, sy = 0, sxx = 0, syy = 0, sxy = 0, k = 0;
  for (let i = 0; i < n; i++) {
    const x = a[i], y = b[i];
    if (x == null || y == null || isNaN(x) || isNaN(y)) continue;
    sx += x; sy += y;
    sxx += x * x; syy += y * y;
    sxy += x * y;
    k++;
  }
  if (k < 2) return null;
  const num = k * sxy - sx * sy;
  const den = Math.sqrt((k * sxx - sx * sx) * (k * syy - sy * sy));
  if (den === 0 || !isFinite(den)) return null;
  return num / den;
}

function correlationMatrix(seriesEntries) {
  const labels = seriesEntries.map(([name]) => name);
  const arrays = seriesEntries.map(([, arr]) => sliceRange(arr));
  const n = labels.length;
  const matrix = [];
  for (let i = 0; i < n; i++) {
    const row = [];
    for (let j = 0; j < n; j++) {
      row.push(i === j ? 1 : pearson(arrays[i], arrays[j]));
    }
    matrix.push(row);
  }
  return { labels, matrix };
}

const chartColors = {
  blue: '#4da3ff',
  blueFill: 'rgba(77, 163, 255, 0.18)',
  green: '#2ecc71',
  greenFill: 'rgba(46, 204, 113, 0.18)',
  amber: '#ffb84d',
  amberFill: 'rgba(255, 184, 77, 0.22)',
  red: '#ff6b6b',
  redFill: 'rgba(255, 107, 107, 0.22)',
  grid: 'rgba(255, 255, 255, 0.08)',
  text: '#97a5bf'
};

const compoundAccent = {
  compound1: { line: chartColors.red, fill: chartColors.redFill, name: 'Compound 1' },
  compound2: { line: chartColors.amber, fill: chartColors.amberFill, name: 'Compound 2' }
};

let combinedChart = null;
let currentCompound = 'compound1';
let rangeStart = 0;
let rangeEnd = analysisData.labels.length - 1;
const hiddenDatasetLabels = new Set();

function adaptivePointRadius() {
  const n = rangeEnd - rangeStart + 1;
  if (n <= 2) return 5;
  if (n <= 7) return 3;
  if (n <= 14) return 2;
  return 0;
}

function formatDayTick(value) {
  const label = this.getLabelForValue ? this.getLabelForValue(value) : value;
  if (!label || typeof label !== 'string') return label;
  const parts = label.split('-');
  if (parts.length !== 3) return label;
  const [y, m, d] = parts.map(Number);
  const month = new Date(Date.UTC(y, m - 1, d)).toLocaleString('en', { month: 'short' });
  return `${month} ${String(d).padStart(2, '0')}`;
}

function combinedChartOptions() {
  return {
    responsive: true,
    maintainAspectRatio: false,
    interaction: { mode: 'index', intersect: false },
    plugins: {
      legend: {
        labels: { color: chartColors.text, usePointStyle: true, boxWidth: 8 }
      },
      tooltip: {
        backgroundColor: 'rgba(16, 27, 52, 0.95)',
        borderColor: 'rgba(255,255,255,0.12)',
        borderWidth: 1,
        titleColor: '#f8fbff',
        bodyColor: '#e5eefc'
      }
    },
    scales: {
      x: {
        grid: { color: chartColors.grid, drawTicks: false },
        ticks: {
          color: chartColors.text,
          autoSkip: true,
          maxTicksLimit: 12,
          maxRotation: 0,
          callback: formatDayTick
        }
      },
      yTemp: {
        type: 'linear',
        position: 'left',
        title: { display: true, text: 'Temperature (°C)', color: chartColors.red },
        grid: { color: chartColors.grid, drawTicks: false },
        ticks: { color: chartColors.red }
      },
      yHum: {
        type: 'linear',
        position: 'right',
        title: { display: true, text: 'Humidity (%)', color: chartColors.blue },
        grid: { drawOnChartArea: false },
        ticks: { color: chartColors.blue }
      },
      yHeat: {
        type: 'linear',
        position: 'right',
        title: { display: true, text: 'Heating (kWh)', color: chartColors.amber },
        grid: { drawOnChartArea: false },
        ticks: { color: chartColors.amber },
        offset: true
      }
    }
  };
}

const zoneStyle = {
  top: { dash: [], alpha: 1.00 },
  middle: { dash: [6, 4], alpha: 0.90 },
  bottom: { dash: [2, 3], alpha: 0.80 }
};

const zoneColor = {
  temperature: {
    top: '#ff6b6b',
    middle: '#ff9557',
    bottom: '#ffc46b'
  },
  humidity: {
    top: '#4da3ff',
    middle: '#6dd3ff',
    bottom: '#2ecc71'
  }
};

const zoneLabel = { top: 'Top', middle: 'Middle', bottom: 'Bottom' };

function sliceRange(arr) {
  return arr.slice(rangeStart, rangeEnd + 1);
}

function zoneDatasets(metric, zones, yAxisID) {
  return ['top', 'middle', 'bottom'].map((zone) => {
    const label = `${metric === 'temperature' ? 'Temp' : 'Humidity'} · ${zoneLabel[zone]}`;
    return {
      label,
      data: sliceRange(zones[zone]),
      yAxisID,
      borderColor: zoneColor[metric][zone],
      backgroundColor: zoneColor[metric][zone],
      tension: 0.3,
      fill: false,
      pointRadius: adaptivePointRadius(),
      pointHoverRadius: 5,
      borderWidth: 2,
      borderDash: zoneStyle[zone].dash,
      hidden: hiddenDatasetLabels.has(label)
    };
  });
}

const phaseBackgroundPlugin = {
  id: 'phaseBackground',
  beforeDatasetsDraw(chart, _args, opts) {
    const phases = opts && opts.phases;
    if (!phases || !phases.length) return;

    const { ctx, chartArea, scales } = chart;
    const xScale = scales.x;
    if (!xScale || !chartArea) return;

    const n = phases.length;
    for (let i = 0; i < n; i++) {
      const phaseId = phases[i];
      const phase = PHASES[phaseId];
      if (!phase) continue;

      const xCenter = xScale.getPixelForValue(i);
      const xPrev = i > 0 ? xScale.getPixelForValue(i - 1) : null;
      const xNext = i < n - 1 ? xScale.getPixelForValue(i + 1) : null;

      const xStart = xPrev == null ? chartArea.left : (xPrev + xCenter) / 2;
      const xEnd = xNext == null ? chartArea.right : (xCenter + xNext) / 2;

      ctx.save();
      ctx.fillStyle = phase.band;
      ctx.fillRect(
        xStart,
        chartArea.top,
        xEnd - xStart,
        chartArea.bottom - chartArea.top
      );

      ctx.fillStyle = phase.ring;
      ctx.fillRect(xStart + 1, chartArea.top, Math.max(0, xEnd - xStart - 2), 3);
      ctx.restore();
    }
  }
};

if (typeof Chart !== 'undefined' && Chart.register) {
  Chart.register(phaseBackgroundPlugin);
}

function buildPhaseArray(compoundKey) {
  return getPhaseSeries(compoundKey).slice(rangeStart, rangeEnd + 1);
}

function buildCombinedChart(compoundKey) {
  const ctx = document.getElementById('chart-combined');
  if (!ctx) return null;
  const series = analysisData[compoundKey];

  const outsideLabel = 'Outside · Temperature';
  const heatingLabel = 'Heating (kWh)';

  const datasets = [
    ...zoneDatasets('temperature', series.temperature, 'yTemp'),
    {
      label: outsideLabel,
      data: sliceRange(analysisData.outdoor.temperature),
      yAxisID: 'yTemp',
      borderColor: '#6dd3ff',
      backgroundColor: 'rgba(109, 211, 255, 0.18)',
      tension: 0.3,
      fill: false,
      pointRadius: adaptivePointRadius(),
      pointHoverRadius: 5,
      borderWidth: 2,
      borderDash: [1, 3],
      hidden: hiddenDatasetLabels.has(outsideLabel)
    },
    ...zoneDatasets('humidity', series.humidity, 'yHum'),
    {
      label: heatingLabel,
      data: sliceRange(series.heating),
      yAxisID: 'yHeat',
      borderColor: chartColors.amber,
      backgroundColor: chartColors.amberFill,
      tension: 0.3,
      fill: false,
      pointRadius: adaptivePointRadius(),
      pointHoverRadius: 5,
      borderWidth: 2,
      borderDash: [8, 4],
      hidden: hiddenDatasetLabels.has(heatingLabel)
    }
  ];

  const options = combinedChartOptions();
  options.plugins = options.plugins || {};
  options.plugins.phaseBackground = { phases: buildPhaseArray(compoundKey) };

  return new Chart(ctx, {
    type: 'line',
    data: {
      labels: sliceRange(analysisData.labels),
      datasets
    },
    options
  });
}

function renderPhaseLegend() {
  const root = document.getElementById('phase-legend');
  if (!root) return;
  root.innerHTML = PHASE_ORDER.map((id) => {
    const p = PHASES[id];
    return `
      <span class="phase-chip phase-${p.id}" title="${p.description}">
        <span class="phase-dot"></span>${p.label}
      </span>
    `;
  }).join('');
}

function captureHiddenState() {
  if (!combinedChart) return;
  combinedChart.data.datasets.forEach((ds, idx) => {
    if (!combinedChart.isDatasetVisible(idx)) {
      hiddenDatasetLabels.add(ds.label);
    } else {
      hiddenDatasetLabels.delete(ds.label);
    }
  });
}

let pickerMode = 'range';
let weekBuckets = [];
let monthBuckets = [];

function buildPickerBuckets() {
  weekBuckets = [];
  monthBuckets = [];
  if (!analysisData.labels.length) return;

  const monthsMap = new Map();
  analysisData.labels.forEach((iso, i) => {
    const key = iso.slice(0, 7);
    if (!monthsMap.has(key)) monthsMap.set(key, { start: i, end: i });
    else monthsMap.get(key).end = i;
  });
  for (const [key, b] of monthsMap) {
    const [y, m] = key.split('-').map(Number);
    const label = new Date(Date.UTC(y, m - 1, 1))
      .toLocaleString('en', { month: 'long', year: 'numeric' });
    monthBuckets.push({ key, label, start: b.start, end: b.end });
  }

  let currentKey = null;
  let current = null;
  analysisData.labels.forEach((iso, i) => {
    const [y, m, d] = iso.split('-').map(Number);
    const date = new Date(Date.UTC(y, m - 1, d));
    const dayOfWeek = date.getUTCDay();
    const offset = (dayOfWeek + 6) % 7;
    const monday = new Date(date);
    monday.setUTCDate(date.getUTCDate() - offset);
    const weekKey = monday.toISOString().slice(0, 10);
    if (weekKey !== currentKey) {
      currentKey = weekKey;
      const month = monday.toLocaleString('en', { month: 'short' });
      const label = `Week of ${month} ${monday.getUTCDate()}, '${String(monday.getUTCFullYear()).slice(2)}`;
      current = { key: weekKey, label, start: i, end: i };
      weekBuckets.push(current);
    } else {
      current.end = i;
    }
  });
}

function populatePickerSelects() {
  const weekEl = document.getElementById('picker-week');
  const monthEl = document.getElementById('picker-month');
  if (weekEl) {
    weekEl.innerHTML = weekBuckets
      .map((b) => `<option value="${b.key}">${b.label}</option>`)
      .join('');
  }
  if (monthEl) {
    monthEl.innerHTML = monthBuckets
      .map((b) => `<option value="${b.key}">${b.label}</option>`)
      .join('');
  }
  const dayEl = document.getElementById('picker-day');
  if (dayEl && analysisData.labels.length) {
    dayEl.min = analysisData.labels[0];
    dayEl.max = analysisData.labels[analysisData.labels.length - 1];
  }
}

function findBucketForIndex(buckets, idx) {
  return buckets.find((b) => idx >= b.start && idx <= b.end) || buckets[0];
}

function setPickerMode(mode) {
  pickerMode = mode;
  document.querySelectorAll('.picker-mode').forEach((b) => {
    const active = b.dataset.mode === mode;
    b.classList.toggle('active', active);
    b.setAttribute('aria-selected', active ? 'true' : 'false');
  });
  document.querySelectorAll('.picker-pane').forEach((p) => {
    const show = p.dataset.pane === mode;
    if (show) p.removeAttribute('hidden');
    else p.setAttribute('hidden', '');
  });
  syncActiveModePicker();
}

function syncActiveModePicker() {
  if (pickerMode === 'day') {
    const el = document.getElementById('picker-day');
    if (el) el.value = analysisData.labels[rangeStart] || '';
  } else if (pickerMode === 'week') {
    const el = document.getElementById('picker-week');
    if (el) el.value = findBucketForIndex(weekBuckets, rangeStart).key;
  } else if (pickerMode === 'month') {
    const el = document.getElementById('picker-month');
    if (el) el.value = findBucketForIndex(monthBuckets, rangeStart).key;
  }
}

function applyPickerSelection(modeOverride) {
  const mode = modeOverride || pickerMode;
  if (mode === 'day') {
    const el = document.getElementById('picker-day');
    if (!el || !el.value) return;
    const idx = dateToIndex(el.value);
    rangeStart = rangeEnd = idx;
  } else if (mode === 'week') {
    const el = document.getElementById('picker-week');
    const b = weekBuckets.find((x) => x.key === el.value);
    if (!b) return;
    rangeStart = b.start;
    rangeEnd = b.end;
  } else if (mode === 'month') {
    const el = document.getElementById('picker-month');
    const b = monthBuckets.find((x) => x.key === el.value);
    if (!b) return;
    rangeStart = b.start;
    rangeEnd = b.end;
  }
  syncRangeUI();
  setPresetActive(detectPreset() || '__custom__');
  renderAllCharts(currentCompound);
}

function navigatePicker(direction) {
  if (pickerMode === 'day') {
    const next = Math.max(0, Math.min(analysisData.labels.length - 1, rangeStart + direction));
    rangeStart = rangeEnd = next;
  } else if (pickerMode === 'week') {
    const i = weekBuckets.findIndex((b) => rangeStart >= b.start && rangeStart <= b.end);
    const nextI = Math.max(0, Math.min(weekBuckets.length - 1, i + direction));
    const b = weekBuckets[nextI];
    rangeStart = b.start;
    rangeEnd = b.end;
  } else if (pickerMode === 'month') {
    const i = monthBuckets.findIndex((b) => rangeStart >= b.start && rangeStart <= b.end);
    const nextI = Math.max(0, Math.min(monthBuckets.length - 1, i + direction));
    const b = monthBuckets[nextI];
    rangeStart = b.start;
    rangeEnd = b.end;
  } else {
    return;
  }
  syncRangeUI();
  syncActiveModePicker();
  setPresetActive(detectPreset() || '__custom__');
  renderAllCharts(currentCompound);
}

const MIN_SPAN_DAYS = 1;

function dateToIndex(iso) {
  const idx = analysisData.labels.indexOf(iso);
  if (idx !== -1) return idx;
  for (let i = 0; i < analysisData.labels.length; i++) {
    if (analysisData.labels[i] >= iso) return i;
  }
  return analysisData.labels.length - 1;
}

function formatDateISO(iso) {
  if (!iso) return '';
  const [y, m, d] = iso.split('-').map(Number);
  const date = new Date(Date.UTC(y, m - 1, d));
  const month = date.toLocaleString('en', { month: 'short' });
  const yy = String(y).slice(2);
  return `${month} ${d}, '${yy}`;
}

function setPresetActive(preset) {
  document.querySelectorAll('.range-preset').forEach((b) => {
    b.classList.toggle('active', b.dataset.preset === preset);
  });
}

function applyPreset(preset) {
  const last = analysisData.labels.length - 1;
  if (last < 0) return;

  const map = { '1M': 30, '3M': 90, '6M': 180 };
  if (preset === 'ALL') {
    rangeStart = 0;
    rangeEnd = last;
  } else {
    const span = map[preset] ?? 30;
    rangeEnd = last;
    rangeStart = Math.max(0, last - span + 1);
  }
  syncRangeUI();
  setPresetActive(preset);
  renderAllCharts(currentCompound);
}

function detectPreset() {
  const last = analysisData.labels.length - 1;
  const span = rangeEnd - rangeStart + 1;
  if (rangeStart === 0 && rangeEnd === last) return 'ALL';
  if (rangeEnd === last) {
    if (span === 30) return '1M';
    if (span === 90) return '3M';
    if (span === 180) return '6M';
  }
  return null;
}

function updateRangeFill() {
  const fill = document.getElementById('range-track-fill');
  if (!fill) return;
  const last = analysisData.labels.length - 1;
  if (last <= 0) return;
  const leftPct = (rangeStart / last) * 100;
  const rightPct = (rangeEnd / last) * 100;
  fill.style.left = leftPct + '%';
  fill.style.right = (100 - rightPct) + '%';
}

function updateRangeReadout() {
  const fromEl = document.getElementById('range-readout-from');
  const toEl = document.getElementById('range-readout-to');
  const spanEl = document.getElementById('range-readout-span');
  if (fromEl) fromEl.textContent = formatDateISO(analysisData.labels[rangeStart]);
  if (toEl) toEl.textContent = formatDateISO(analysisData.labels[rangeEnd]);
  if (spanEl) {
    const days = rangeEnd - rangeStart + 1;
    spanEl.textContent = `· ${days} day${days === 1 ? '' : 's'}`;
  }
}

function syncRangeUI() {
  const fromEl = document.getElementById('range-from');
  const toEl = document.getElementById('range-to');
  if (fromEl) fromEl.value = String(rangeStart);
  if (toEl) toEl.value = String(rangeEnd);
  updateRangeFill();
  updateRangeReadout();
}

function initRangePicker() {
  const fromEl = document.getElementById('range-from');
  const toEl = document.getElementById('range-to');
  if (!fromEl || !toEl || !analysisData.labels.length) return;

  const last = analysisData.labels.length - 1;
  [fromEl, toEl].forEach((el) => {
    el.min = '0';
    el.max = String(last);
    el.step = '1';
  });

  buildPickerBuckets();
  populatePickerSelects();
  syncRangeUI();
  syncActiveModePicker();

  const onInput = (source) => {
    let from = parseInt(fromEl.value, 10);
    let to = parseInt(toEl.value, 10);

    if (source === 'from' && from > to) {
      from = to;
      fromEl.value = String(from);
    } else if (source === 'to' && to < from) {
      to = from;
      toEl.value = String(to);
    }

    rangeStart = from;
    rangeEnd = to;
    updateRangeFill();
    updateRangeReadout();
    const preset = detectPreset();
    setPresetActive(preset || '__custom__');
    renderAllCharts(currentCompound);
  };

  fromEl.addEventListener('input', () => onInput('from'));
  toEl.addEventListener('input', () => onInput('to'));

  document.querySelectorAll('.range-preset').forEach((btn) => {
    btn.addEventListener('click', () => applyPreset(btn.dataset.preset));
  });

  document.querySelectorAll('.picker-mode').forEach((btn) => {
    btn.addEventListener('click', () => setPickerMode(btn.dataset.mode));
  });

  const dayEl = document.getElementById('picker-day');
  const weekEl = document.getElementById('picker-week');
  const monthEl = document.getElementById('picker-month');
  if (dayEl) dayEl.addEventListener('change', () => applyPickerSelection('day'));
  if (weekEl) weekEl.addEventListener('change', () => applyPickerSelection('week'));
  if (monthEl) monthEl.addEventListener('change', () => applyPickerSelection('month'));

  document.querySelectorAll('.picker-nav').forEach((btn) => {
    btn.addEventListener('click', () => {
      const dir = parseInt(btn.dataset.dir, 10);
      navigatePicker(dir);
    });
  });
}

function renderAllCharts(compoundKey) {
  if (combinedChart) {
    captureHiddenState();
    combinedChart.destroy();
    combinedChart = null;
  }
  combinedChart = buildCombinedChart(compoundKey);

  renderCorrelationBlock(compoundKey);

  const subtitle = document.getElementById('analysis-subtitle');
  if (subtitle) {
    subtitle.textContent = `Showing ${compoundAccent[compoundKey].name}.`;
  }
}

function corrColor(v) {
  if (v == null || isNaN(v)) return 'rgba(255,255,255,0.04)';
  const t = Math.max(-1, Math.min(1, v));
  const cool = { r: 77, g: 128, b: 235 };
  const white = { r: 230, g: 228, b: 222 };
  const warm = { r: 220, g: 65, b: 65 };
  let r, g, b;
  if (t < 0) {
    const k = 1 + t;
    r = Math.round(cool.r + (white.r - cool.r) * k);
    g = Math.round(cool.g + (white.g - cool.g) * k);
    b = Math.round(cool.b + (white.b - cool.b) * k);
  } else {
    const k = t;
    r = Math.round(white.r + (warm.r - white.r) * k);
    g = Math.round(white.g + (warm.g - white.g) * k);
    b = Math.round(white.b + (warm.b - white.b) * k);
  }
  return `rgb(${r}, ${g}, ${b})`;
}

function corrTextColor(v) {
  if (v == null || isNaN(v)) return 'var(--muted)';
  return Math.abs(v) > 0.45 ? '#ffffff' : '#0b1326';
}

function buildHeatmapTable(labels, matrix) {
  const headerCells = labels
    .map((l) => `<th class="heatmap-colhead"><span>${l}</span></th>`)
    .join('');

  const rows = matrix.map((row, i) => {
    const cells = row
      .map((v) => {
        if (v == null || isNaN(v)) {
          return `<td class="heatmap-cell heatmap-cell--empty">–</td>`;
        }
        const bg = corrColor(v);
        const fg = corrTextColor(v);
        return `<td class="heatmap-cell" style="background:${bg}; color:${fg};">${v.toFixed(2)}</td>`;
      })
      .join('');
    return `<tr><th class="heatmap-rowhead">${labels[i]}</th>${cells}</tr>`;
  }).join('');

  return `
    <table class="heatmap-table">
      <thead><tr><th></th>${headerCells}</tr></thead>
      <tbody>${rows}</tbody>
    </table>
  `;
}

function buildLiveCorrelation(kind, compoundKey) {
  const c = analysisData[compoundKey];
  const o = analysisData.outdoor;

  if (kind === 'temperature') {
    return correlationMatrix([
      ['Heating', c.heating],
      ['Lower', c.temperature.bottom],
      ['Middle', c.temperature.middle],
      ['Upper', c.temperature.top],
      ['Outside', o.temperature]
    ]);
  }
  return correlationMatrix([
    ['Lower', c.humidity.bottom],
    ['Middle', c.humidity.middle],
    ['Upper', c.humidity.top],
    ['Outside', o.humidity]
  ]);
}

function renderHeatmap(containerId, kind, compoundKey) {
  const root = document.getElementById(containerId);
  if (!root) return;
  const { labels, matrix } = buildLiveCorrelation(kind, compoundKey);
  root.innerHTML = buildHeatmapTable(labels, matrix);
}

function renderCorrelationBlock(compoundKey) {
  renderHeatmap('heatmap-temp', 'temperature', compoundKey);
  renderHeatmap('heatmap-hum', 'moisture', compoundKey);
}

function initAnalysisCharts() {
  if (typeof Chart === 'undefined') {
    console.warn('Chart.js is not loaded.');
    return;
  }
  renderPhaseLegend();
  initRangePicker();
  renderAllCharts(currentCompound);

  document.querySelectorAll('.compound-btn').forEach((btn) => {
    btn.addEventListener('click', () => {
      const compoundKey = btn.dataset.compound;
      if (!compoundKey || compoundKey === currentCompound) return;

      document.querySelectorAll('.compound-btn').forEach((b) => {
        const active = b === btn;
        b.classList.toggle('active', active);
        b.setAttribute('aria-selected', active ? 'true' : 'false');
      });

      currentCompound = compoundKey;
      renderAllCharts(currentCompound);
    });
  });

  initGiBenchmark();
}

/* ==========================================================================
   GI (Germination Index) reference panels
   Pure reference reproduction of the 2x2 notebook figure:
   pH / Temperature / Moisture / C/N ratio, each with GI overlaid on a second
   axis and a red dotted line at the 80 % maturity threshold.
   ========================================================================== */
const GI_DATA = APP_DATA.gi || null;

// Colour per panel (kept in sync with the notebook styling)
const GI_PANELS = [
  { id: 'ph',       canvas: 'gi-chart-ph',       label: 'pH',                   color: '#4b8bff', unit: '',   refKey: 'pH'       },
  { id: 'temp',     canvas: 'gi-chart-temp',     label: 'Temperature (°C)',     color: '#ff7a59', unit: '°C', refKey: 'temp'     },
  { id: 'moisture', canvas: 'gi-chart-moisture', label: 'Moisture content (%)', color: '#7b6cff', unit: '%',  refKey: 'moisture' },
  { id: 'cn',       canvas: 'gi-chart-cn',       label: 'C/N ratio',            color: '#c88640', unit: '',   refKey: 'cn'       }
];

const GI_MATURITY = 80; // GI % threshold for "mature, phytotoxin-free" compost
const giCharts = {};

function initGiBenchmark() {
  if (!GI_DATA || !GI_DATA.reference || !GI_DATA.reference.available) {
    const wrapper = document.querySelector('.gi-section');
    if (wrapper) {
      wrapper.innerHTML =
        '<p class="gi-intro">GI reference data is not available. ' +
        'Run <code>python3 python/build_data.py</code> with the reference CSV in place.</p>';
    }
    return;
  }

  const countEl = document.getElementById('gi-sample-count');
  if (countEl && GI_DATA.reference.sampleCount) {
    countEl.textContent = GI_DATA.reference.sampleCount.toLocaleString();
  }

  GI_PANELS.forEach((panel) => buildGiChart(panel));
}

function buildGiChart(panel) {
  const ctx = document.getElementById(panel.canvas);
  if (!ctx) return;

  const stages = GI_DATA.stages || GI_DATA.reference.stages;
  const refSeries = GI_DATA.reference.series[panel.refKey];
  const giSeries  = GI_DATA.reference.series.gi;

  const datasets = [
    {
      label: panel.label,
      data: refSeries,
      borderColor: panel.color,
      backgroundColor: hexToRgba(panel.color, 0.15),
      borderWidth: 2.5,
      tension: 0.25,
      pointRadius: 4,
      pointHoverRadius: 5,
      yAxisID: 'y'
    },
    {
      label: 'GI (%)',
      data: giSeries,
      borderColor: '#1dbf73',
      backgroundColor: 'transparent',
      borderWidth: 2,
      borderDash: [6, 4],
      tension: 0.25,
      pointRadius: 3.5,
      pointStyle: 'rectRot',
      pointHoverRadius: 5,
      yAxisID: 'yGi'
    }
  ];

  giCharts[panel.id] = new Chart(ctx, {
    type: 'line',
    data: { labels: stages, datasets },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      interaction: { mode: 'index', intersect: false },
      plugins: {
        legend: {
          position: 'bottom',
          labels: {
            color: '#d1d5db',
            boxWidth: 10,
            boxHeight: 10,
            padding: 10,
            font: { size: 11 }
          }
        },
        tooltip: {
          backgroundColor: 'rgba(11, 19, 38, 0.94)',
          borderColor: 'rgba(255,255,255,0.08)',
          borderWidth: 1,
          padding: 10,
          titleColor: '#fff',
          bodyColor: '#d1d5db',
          callbacks: {
            label(ctx2) {
              const val = ctx2.parsed.y;
              if (val == null) return `${ctx2.dataset.label}: —`;
              const unit = ctx2.dataset.yAxisID === 'yGi' ? '%' : (panel.unit || '');
              return `${ctx2.dataset.label}: ${val.toFixed(2)}${unit ? ' ' + unit : ''}`;
            }
          }
        },
        // Draw the 80 % maturity line using a lightweight plugin.
        gi80Line: { threshold: GI_MATURITY }
      },
      scales: {
        x: {
          ticks: { color: '#9ca3af', font: { size: 11 } },
          grid:  { color: 'rgba(255,255,255,0.05)' },
          title: { display: true, text: 'Compost time (days)', color: '#9ca3af', font: { size: 11 } }
        },
        y: {
          position: 'left',
          ticks: { color: panel.color, font: { size: 11 } },
          grid:  { color: 'rgba(255,255,255,0.05)' },
          title: { display: true, text: panel.label, color: panel.color, font: { size: 11 } }
        },
        yGi: {
          position: 'right',
          min: 0,
          max: 110,
          ticks: { color: '#1dbf73', font: { size: 11 }, callback: (v) => `${v}%` },
          grid:  { drawOnChartArea: false },
          title: { display: true, text: 'GI (%)', color: '#1dbf73', font: { size: 11 } }
        }
      }
    },
    plugins: [gi80LinePlugin]
  });
}

function hexToRgba(hex, alpha) {
  const h = hex.replace('#', '');
  const full = h.length === 3 ? h.split('').map((c) => c + c).join('') : h;
  const r = parseInt(full.slice(0, 2), 16);
  const g = parseInt(full.slice(2, 4), 16);
  const b = parseInt(full.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

// Chart.js plugin that draws the 80 % GI maturity line on the right axis.
const gi80LinePlugin = {
  id: 'gi80Line',
  afterDraw(chart, _args, opts) {
    const threshold = (opts && opts.threshold) || 80;
    const scale = chart.scales.yGi;
    if (!scale) return;
    const y = scale.getPixelForValue(threshold);
    const { left, right } = chart.chartArea;
    const ctx = chart.ctx;

    ctx.save();
    ctx.strokeStyle = 'rgba(255, 107, 107, 0.85)';
    ctx.lineWidth = 1.5;
    ctx.setLineDash([3, 4]);
    ctx.beginPath();
    ctx.moveTo(left, y);
    ctx.lineTo(right, y);
    ctx.stroke();

    ctx.setLineDash([]);
    ctx.fillStyle = 'rgba(255, 107, 107, 0.9)';
    ctx.font = '10px system-ui, sans-serif';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'bottom';
    ctx.fillText(`GI ${threshold}% · maturity`, right - 6, y - 3);
    ctx.restore();
  }
};
